// WARNING: This file has automatically been generated on Fri, 22 Jul 2022 22:52:51 EEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package all

/*
#include "DEV_Config.h"
#include "bcm2835.h"
#include "EPD_IT8951.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// IT8951_Load_Img_Info as declared in all/EPD_IT8951.h:54
type IT8951_Load_Img_Info struct {
	Endian_Type        uint16
	Pixel_Format       uint16
	Rotate             uint16
	Source_Buffer_Addr uint32
	Target_Memory_Addr uint32
	ref66739e64        *C.IT8951_Load_Img_Info
	allocs66739e64     interface{}
}

// IT8951_Area_Img_Info as declared in all/EPD_IT8951.h:62
type IT8951_Area_Img_Info struct {
	Area_X         uint16
	Area_Y         uint16
	Area_W         uint16
	Area_H         uint16
	refe518aace    *C.IT8951_Area_Img_Info
	allocse518aace interface{}
}

// IT8951_Dev_Info as declared in all/EPD_IT8951.h:72
type IT8951_Dev_Info struct {
	Panel_W        uint16
	Panel_H        uint16
	Memory_Addr_L  uint16
	Memory_Addr_H  uint16
	FW_Version     [8]uint16
	LUT_Version    [8]uint16
	refab7ec1bd    *C.IT8951_Dev_Info
	allocsab7ec1bd interface{}
}
